name = "paas"
main = ".svelte-kit/cloudflare/_worker.js"
compatibility_date = "2025-01-01"
# compatibility_flags = ["nodejs_compat"]

[assets]
binding = "ASSETS"
directory = ".svelte-kit/cloudflare"

[build]
command = "pnpm run build-edge"

[env.production]
vars = { NODE_ENV = "production" }

